[package]
name = "ibex"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "./core" }
grass = "0.13.1"
macros = { path = "./macros" }
# , optional = true }

# [features]
# macros = ["dep:macros"]
